### ISSUE TITLE
DateTime Field

### ISSUE THREAD

**Issue by jouniikaheimo** [masterix21/x-blade-components#5]
flatpickr custom config, how i can set 24h time and enable time ? if i understand code correct that is not possible now ?

**Comment by masterix21** [comment]
Hi @jouniikaheimo, thanks for your interest in our package.

At the moment no, but in the next hours I will release the datetime-field to help you.

**Comment by jouniikaheimo** [comment]
ah thx.. i wait that, and how about editors ckeditor or something other textarea ?

**Comment by masterix21** [comment]
Yes, it's in the todo-list

**Comment by masterix21** [comment]
https://github.com/masterix21/x-blade-components/wiki/Form-DateField

Added the support to time using customConfig parameter. Follow the documentation.

Thanks for your issue.
