### ISSUE TITLE
cannot display selected value

### ISSUE THREAD

**Issue by santhika29** [masterix21/x-blade-components#6]
how to display the selected value on select components?
i try your sample but after i select the value, it always reset to the default value....
any advice?

**Comment by masterix21** [comment]
Hi @santhika29, are you using the value parameter? 

Example:
```blade
<x-bc-form:select-field :options="$this->tabs" wire:model="tab" :value="$tab" />
```

**Comment by santhika29** [comment]
thank u my friend
